clean:
	@rm -r spaceflights


test:
	@cookiecutter git@bitbucket.org:daemonsolutions/daemn-kedro-template.git

docker: 
	@chmod +x ./spaceflights/check-docker-img.sh
	@./spaceflights/check-docker-img.sh
